# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadmanapp', '0002_auto_20160120_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadmanswitch',
            name='name',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
    ]
