# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadmanapp', '0003_deadmanswitch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New ContactType', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_number',
            new_name='contact_info',
        ),
        migrations.AlterField(
            model_name='deadmanswitch',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deadmanapp.Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deadmanapp.ContactType'),
        ),
    ]
