# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadmanapp', '0006_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password_expired',
            field=models.BooleanField(default=False, verbose_name='Must change password on next login'),
        ),
    ]
