# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 15:57
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadmanapp', '0007_auto_20160122_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password_expired',
            field=models.BooleanField(default=False, verbose_name='Password expired'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
